### ISSUE TITLE
组件显示在statusbar下面

### ISSUE THREAD

**Issue by sun-sheng** [magicismight/react-native-root-siblings#2]
你好，使用RootSiblings添加的组件，显示在statusbar下方，我想让组件能够覆盖statusbar，请问有什么办法吗？

**Comment by NbZzp** [comment]
解决了吗

**Comment by guokangf** [comment]
为什么不使用`Model`组件呢？

**Comment by relign** [comment]
Can you speak English ?

**Comment by magicismight** [comment]
貌似 native 也没有什么好办法可以遮挡 statusbar 吧，statusbar 是系统组件，要隐藏只有调 api 去隐藏
