### ISSUE TITLE
_reactNative.AppRegistry.setWrapperComponentProvider is not a function

### ISSUE THREAD

**Issue by wangsiyuan0215** [magicismight/react-native-root-siblings#21]
When I updated react-native-root-toast to the new version 2.1.0, I got an error like this.
Oh, my version of React Native is 0.46.3.

**Comment by wangsiyuan0215** [comment]
After searching the doc of React Native for AppRegister, I didn`t find the function which is `AppRegistry.setWrapperComponentProvider`, so any solutions?

**Comment by Andarist** [comment]
It's there - https://facebook.github.io/react-native/docs/appregistry.html#setwrappercomponentprovider

**Comment by sunnylqm** [comment]
Unfortunately setWrapperComponentProvider is RN 0.47+

**Comment by zza19900808** [comment]
解决了么？

**Comment by zza19900808** [comment]
rn版本是0.45，		
"react-native-root-modal": "^1.1.1",
"react-native-root-siblings": "^1.2.1",
最终选择降级解决问题
