### ISSUE TITLE
1.2到1.3很坑爹的变化

### ISSUE THREAD

**Issue by djkdeveloper** [magicismight/react-native-root-siblings#22]
骚年 更新的时候最好更新下对应rn的版本号，现在跑的项目之前依赖这个包 然后当时用的是    "react-native-root-siblings": "^1.0.7"
然后这次来人把包删了重新install后发现启动报错。。。定位后发现1.2.0和1.3.0 对rn的一个类的引入发生了变化EventEmitter  这个类。。。。。。。。

**Comment by heiheiLqq** [comment]
请问结局了么  我装的1.21 每次装完显示1.30  然后就会找不到EventEmitter

**Comment by djkdeveloper** [comment]
解决了   在你的项目中把它的依赖写到你自己的packjson文件中 主要是		"react-native-root-siblings": "1.2.0"
这个依赖

**Comment by djkdeveloper** [comment]
解决了 在你的项目中把它的依赖写到你自己的packjson文件中 主要是	"react-native-root-siblings": "1.2.0"
这个依赖
