### ISSUE TITLE
can not work with react-redux

### ISSUE THREAD

**Issue by youngpink** [magicismight/react-native-root-siblings#24]
in a handleClick function, I update the rootSiblings like this, 
`handleClick() {
        this.progressBar.update(
          <ProgressBar />
        );
} `

and  in ProgressBar component, I 
`import React, { PropTypes } from 'react';
import { connect } from 'react-redux';
import { View } from 'react-native';
const getFinishedWidth = progress => ({ width: progress * totalWidth });
const getUnfinishedWidth = progress => ({ width: (1 - progress) * totalWidth });
function CustomerReassignProgressBar(props) {
    const { progress } = props;
    return (
          <View style={styles.bar}>
            <View style={getFinishedWidth(progress)} />
            <View style={getUnfinishedWidth(progress)} />
          </View>
    );
}
CustomerReassignProgressBar.propTypes = {
  progress: PropTypes.number,
};
const mapStateToProps = state => ({
  progress: state.batchReassignProgress,
});
export default connect(mapStateToProps)(ProgressBar);
`

then, when calling handleClick(), the app crushed, the error is, 'Could not find "store" in either the context or props of "Connect(ProgressBar)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(ProgressBar)".'

does anyone know this problem?

**Comment by niuniubuniu** [comment]
<Provider store={store}>
<ProgressBar />   
</Provider> 
这样用就行了

**Comment by MaxiSantos** [comment]
@youngpink I'm having the same issue.
@niuniubuniu I fixed by adding my store as a props in the component I'm using with react-native-root.siblings. But then I got `redux-persist: cannot process cyclical state` at a random flow.

**Comment by sunnylqm** [comment]
Need to pass redux store as the third argument to constructor or update method.
https://github.com/magicismight/react-native-root-siblings/blob/master/index.d.ts#L2
The redux-persist issue seems unrelated. Feel free to open a new issue if you still encounter that issue with root-siblings only. @MaxiSantos
