### ISSUE TITLE
Issue with latest RN 0.56-rc.3

### ISSUE THREAD

**Issue by deehuey** [magicismight/react-native-root-siblings#29]
Not entirely sure what the issue here is, but it seems in babel 7 it does not like the `export default class { ... }` syntax, as I am unable to build a production release.

In development it is working fine, but trying to build is throwing me a 
```
/Users/dan/code/app/node_modules/react-native-root-siblings/index.js: /Users/dan/code/app/node_modules/react-native-root-siblings/index.js: Exporting local "_default", which is not declared. (This is an error on an internal node. Probably an internal error.)
```

Fixed by adding any gibberish after the class keyword (`export default class Chicken { ... }`)

**Comment by mailworks** [comment]
the same issue~

**Comment by joey3060** [comment]
same issue, that will cause CD bug....

**Comment by carrawao** [comment]
@deehuey @mailworks @joey3060 when are you guys going to merge these changes and release the fix? We are having real problems building our app because of this!

**Comment by soumyamishra89** [comment]
when is the merge happening? It blocks the building of the app

**Comment by sunnylqm** [comment]
Fixed in https://github.com/magicismight/react-native-root-siblings/commit/1f95f1552e30fc661d9bf4f8f54ae88aad6b5b21
