### ISSUE TITLE
Customization of element position in App's tree

### ISSUE THREAD

**Issue by huston007** [magicismight/react-native-root-siblings#3]
Hello and thank you for the great component!
Unfortunately, it doesn't feet my needs.
I have such `render` function of my app:
```js
  render() {
    return (
      <Provider store={store}>
        <ActionSheet ref={component => this._actionSheetRef = component}>
          <View>
            {Router.renderNavigatorView({initialRoute: Router.routes.Home})}
            <Toast ref={toast => setNotificationComponent(toast)}/>
          </View>
        </ActionSheet>
      </Provider>
    );
  }
```

As you see, I already render `<Toast/>` component right after the current view. It allows me to not show Toast over the whole app, but only for current view. For example, if you swipe view back, the toast dissapears.

I would really like to use same way with root-siblings (to display modal component for current view only, not for whole app). But it is impossible with custom implementation.

**Comment by wulucxy** [comment]
@huston007 did you solve this?

**Comment by huston007** [comment]
@wulucxy unfortunately no, i didn't do anything with that.

**Comment by sunnylqm** [comment]
You can create a custom view to meet that needs. As the name implies root-siblings will always insert itself into root level.
