### ISSUE TITLE
Build error with RN 0.56

### ISSUE THREAD

**Issue by ithieund** [magicismight/react-native-root-siblings#33]
Hi,
I'm facing with this issue https://github.com/magicismight/react-native-root-toast/issues/79

Can you please update this library soon?
Thanks.

**Comment by jgcmarins** [comment]
for those who are stuck on this, just use package.json `resolutions`:
```
"resolutions": {
    "react-native-root-siblings": "git+https://git@github.com/thatjuan/react-native-root-siblings.git#953b71e98e2891e543207e9aaa660d83ccd237a6"
  },
```

**Comment by Jayxiang** [comment]
export default class  ---  export default class Rootsiblings  ok

**Comment by sunnylqm** [comment]
Fixed in https://github.com/magicismight/react-native-root-siblings/commit/1f95f1552e30fc661d9bf4f8f54ae88aad6b5b21
