### ISSUE TITLE
Problem with redux dependency

### ISSUE THREAD

**Issue by luizbaldi** [magicismight/react-native-root-siblings#34]
Hi,

After upgrading from 2.2.0 to 3.1.0 this error started to show up (image below).

Seems like the _react-redux_ dependency is being used without _redux_, so if the project isn't using _redux_ as state management tool it'll break. 

<img width="424" alt="screen shot 2018-09-05 at 18 11 00" src="https://user-images.githubusercontent.com/17226904/45121387-61631080-b137-11e8-8009-79c590952910.png">

To solve this here, I had to manually add _redux_ as dependency even though I use another lib for state management, and this solution isn't good.

I can open a PR adding _redux_ as dependency to fix that. This way the lib will contain all it needs as peer dependencies.

What do you think?

**Comment by younes200** [comment]
Yes, please create a PR for this, redux is unnecessary dependency in this case.

**Comment by luizbaldi** [comment]
Nice! I just opened the pull request here #37 😄
