### ISSUE TITLE
Modal still have higher priority

### ISSUE THREAD

**Issue by St1maSphere** [magicismight/react-native-root-siblings#42]
Hello

I'm trying to use your solution to have some cover View for app in global
But as for Modal - my View still left behind the Modal backdrop

Please, let me know, is it possible to fix such issues

Thanks

**Comment by sunnylqm** [comment]
If you mean the Modal from the react native core, then that is impossible to cover it, cause it is a `native` view. You can consider a js modal instead, like https://github.com/magicismight/react-native-root-modal

**Comment by St1maSphere** [comment]
I see
Thanks for help
