### ISSUE TITLE
AppRegistry.setWrapperComponentProvider not called : nothing rendered

### ISSUE THREAD

**Issue by kamiky** [magicismight/react-native-root-siblings#44]
Hello,

i experience for 2 days now some weird behavior (nothing happens), it was working perfectly before.

i've tracked the issue : `AppRegistry.setWrapperComponentProvider` is not called at all.
`const triggers = []` remains empty and nothing render

I dont think the issue is with react-native-root-sibling, as i said it was working before and i already had the last version.

I think it's deep in react or some side module having a side effect.
Would you have any idea what could cause that ?

`"react-native": "0.57.8"` (i can't upgrade this)
the only module changes i made was to reinstall lottie (it was already installed before though), tried to remove it and see what it does but nothing changes.

**Comment by sunnylqm** [comment]
Use break point to see why it's not called

**Comment by kamiky** [comment]
Ok so, after diving into react-native source code, i understood that AppRegistry.setWrapperComponentProvider is called twice, both with RootSiblingsWrapper but used by different modules :

```
node_modules/react-native-root-siblings/index.js
node_modules/react-native-formik/node_modules/react-native-root-siblings/index.js
```

I think the problem comes from here, everything is being called, AppContainer render `RootSiblingsWrapper` but not the instance i expect.

**Comment by sunnylqm** [comment]
The latest version of react-native-root-siblings has a flag to check whether it is invoked twice. You and all your third parties should use the latest version. (Just delete node_modules and lock files and then reinstall may work)

**Comment by sunnylqm** [comment]
See https://github.com/magicismight/react-native-root-siblings/issues/43
