### ISSUE TITLE
redux和react-native-root-siblings的处理问题

### ISSUE THREAD

**Issue by xuxichen** [magicismight/react-native-root-siblings#49]
您好，我有看您的文档V4.0.0，在入口函数中

`setSiblingWrapper((sibling)=><Provider store={configureStore()}>{sibling}</Provider>`，

但我没明白这段代码如何写入到render()函数中，我的

`<Provider>包裹的是我的react-navigation的组件</Provider>`，

我没明白这里的setSiblingWrapper如何返回给render函数一个组件，也没明白这个sibling参数是用来干嘛的和怎么用的。`

非常感谢您的开源项目

**Comment by sunnylqm** [comment]
写到入口文件，比如index.js或者App.js的靠前的位置（在任何组件render之前）

**Comment by xuxichen** [comment]
> 写到入口文件，比如index.js或者App.js的靠前的位置（在任何组件render之前）

我知道在入口文件写，但怎么写我没弄明白，您能截图或者copy一份入口文件的代码看一下么？我对这个份代码是写在render函数之前还是render函数里面没搞明白，非常非常感谢了

**Comment by sunnylqm** [comment]
就直接在import语句之后写

**Comment by sunnylqm** [comment]
你大概有所误解，这个跟你自己的render函数没有关系，你原先的render不用任何改动

**Comment by xuxichen** [comment]
> 你大概有所误解，这个跟你自己的render函数没有关系，你原先的render不用任何改动

哦哦哦哦，原来如此，非常非常感谢，终于明白了是怎么回事，非常非常感谢。

**Comment by chenyu1990** [comment]
顶层时 new RootSiblings 出来的，怎么用redux??

**Comment by sunnylqm** [comment]
加上setSiblingWrapper即可
