### ISSUE TITLE
Doesn't work well after upgraded to 4.0.0

### ISSUE THREAD

**Issue by evilrescuer** [magicismight/react-native-root-siblings#50]
# Bug

**CAN NOT** create anything using 4.0.0 for react-native 0.60.5
But 3.2.1 works well with the same code

## Environment info

React native info output:

```bash
 System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 562.66 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.2
      System Images: android-24 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5
```

Library version: 4.0.0
Android system version: 8.1.0

## Steps To Reproduce

1. Add the following sample code into React-Native projcet
2. Run-on an android device

Describe what you expected to happen:

1. It works well (can create the element on page)

## Reproducible sample code

```
// TypeScript Code
import React, { ReactNode } from 'react';

const loadingElement: ReactNode = (
  <Text
    style={{
      position: 'absolute',
      backgroundColor: '#10101099',
      height: 80,
      width: 100,
      justifyContent: 'center',
      alignItems: 'center',
      top: 100,
      left: 100,
      zIndex: 10000,
      elevation: 1000,
    }}>
    Can you see me on the page
  </Text>
);

new RootSiblings(loadingElement);  // nothing happened
```

**Comment by magicismight** [comment]
If you are using `react-native-root-modal` and `react-native-root-toast`, please make sure they have updated to the newest versions.
`root-siblings` is not compatible with other modules which are depended on other version of `root-siblings`, make sure you have only one version of `root-siblings` in project.

**Comment by evilrescuer** [comment]
Thanks, it make sense. I checked my `yarn.lock`.
`react-native-root-toast@3.1.2 ` depends on `react-native-root-siblings "^3.0.0"
