### ISSUE TITLE
does'nt work in react-native@0.61.3 and react-navigation@4.0.10

### ISSUE THREAD

**Issue by jiapeng007** [magicismight/react-native-root-siblings#51]

**Comment by magicismight** [comment]
Please make sure you have only one version of `react-native-root-siblings` in your project.
Run
```
npm list | grep react-native-root-siblings
```
to check `react-native-root-siblings` versions in your project dependency tree.

**Comment by jiapeng007** [comment]
![image](https://user-images.githubusercontent.com/32921739/68832360-ae535700-06eb-11ea-885d-78cda10b7f50.png)
only one version 4.0.4

**Comment by jiapeng007** [comment]
![image](https://user-images.githubusercontent.com/32921739/68832729-afd14f00-06ec-11ea-83f2-6ecdf186caf9.png)
I run the code in your example，but the effect is not the same as the gif you provided.

**Comment by magicismight** [comment]
Have you imported `react-native-root-siblings` at the very beginning in your project?
`react-native-root-siblings` should be imported before `AppRegistry.registerComponent` be called.

**Comment by jiapeng007** [comment]
I have imported react-native-root-siblings before AppRegistry.registerComponent, but it does not work.

I have got the answer.  the sibling style add position is ok.
sibling: {
        position: 'absolute',
        left: 0,
        height: 20,
        width: Dimensions.get('window').width / 2,
        backgroundColor: 'blue',
        opacity: 0.5
    }

**Comment by magicismight** [comment]
Cool, I'm closing this now.
Basically the sibling elements is added next to the Root component which is registered by `AppRegistry.registerComponent`. And those siblings elements don't have a default style.
