### ISSUE TITLE
Warning in Expo SDK 36

### ISSUE THREAD

**Issue by wscotten** [magicismight/react-native-root-siblings#54]
Hello!  Thank you for all of the work you do to make this great library.  We really appreciate it!  This warning occurs after we upgraded our app to Expo SDK 36,.  Let me know if you need any other help!

![Image from iOS](https://user-images.githubusercontent.com/24510642/70584072-9e0c8b80-1b74-11ea-9eb2-00a0803c27c4.png)

**Comment by magicismight** [comment]
First disable default injection, put this code at  the very beginning in you project.

```
global.__rootSiblingsDisabled = true;
```

Then wrap your Root component with `RootSiblingParent `.

```
<RootSiblingParent>
  <App />
</RootSiblingParent >
```

Hope this would work on Expo 36

**Comment by wscotten** [comment]
@magicismight I already added the `RootSiblingParent` to the root of the project.  However the 
`global.__rootSiblingsDisabled = true;` did not fix the warning.  Any other possible fixes?

**Comment by devstarman** [comment]
Hi, same problem here :( Also I'd like to point out that this library is indirectly used by other dependencies (in my case react-native-root-toast) and it's highly problematic to use fixes like those mentioned above.

**Comment by magicismight** [comment]
@wscotten make sure you have only one version of root-siblings in your project.
```
npm list react-native-root-siblings
```

**Comment by wscotten** [comment]
@magicismight There is only one installed
![Screen Shot 2019-12-20 at 10 26 53 AM](https://user-images.githubusercontent.com/24510642/71281642-4825a980-2313-11ea-856b-ac9e14aa1219.png)

**Comment by devstarman** [comment]
I just want to add that update to expo 36.0.1 solve this issue.
