### ISSUE TITLE
能增加拖动功能吗，类似视频播放的小窗口，可以随意拖动

### ISSUE THREAD

**Issue by ngxu** [magicismight/react-native-root-siblings#57]
非常感谢作者，已经投入到项目中使用

**Comment by ngxu** [comment]
是可以自己添加这个拖拽功能，手势结合动画实现，但是RN的手势，动画不是特别流畅，高端机影响不大，特别是中配低配手机，有点糟糕。不知道能不能原生实现呢

**Comment by magicismight** [comment]
你提的功能和 root-siblings 这个库没啥直接关系，要实现流畅的手势动画参考这个库：https://github.com/software-mansion/react-native-gesture-handler
