### ISSUE TITLE
How to use it with Mobx

### ISSUE THREAD

**Issue by flatcoke** [magicismight/react-native-root-siblings#61]
my app.jsx code like 
```jsx
const App: React.ReactFragment = () => {
  const stores = initializeStore()
  return (
    <Provider value={stores}>
      <React.Fragment>
        <SafeAreaProvider>
          <StatusBar barStyle="dark-content" />
          <AppNavigator />
        </SafeAreaProvider>
      </React.Fragment>
    </Provider>
  )
}
export default App
```
How to combine with that

**Comment by sunnylqm** [comment]
Nothing special. Use it as normal.

**Comment by flatcoke** [comment]
> Nothing special. Use it as normal.

But can not get any store in a component with RootSiblings.
There is a solution on document for redux using `setSiblingWrapper`  like
```jsx
import { setSiblingWrapper } from 'react-native-root-siblings';
import { Provider } from 'react-redux';

// const store = ... get store;

// Call this before using redux context inside RootSiblings.
setSiblingWrapper((sibling) => <Provider store={store}>{sibling}</Provider>);
```
I tried the above method but it didn't work

**Comment by sunnylqm** [comment]
Since you are using mobx, why you import a redux provider?

**Comment by flatcoke** [comment]
@sunnylqm 

I mean there is a redux provider functions but why no one for mobx? I never use a redux provider as you said. it can not use store in component by RootSiblings. In short I created a component using that function and got an error when accessing the store from within that component.

**Comment by sunnylqm** [comment]
That is an `example`.
```
import whateverProvider from 'whateverProviderThatYourLibraryNeeds';
```

**Comment by sunnylqm** [comment]
And by the way you can also use hooks which does not require a provider.

**Comment by flatcoke** [comment]
Okay. I will try that. Probably because I'm immature
