### ISSUE TITLE
4.0.6版本如何使用？

### ISSUE THREAD

**Issue by niu-da-li** [magicismight/react-native-root-siblings#63]
你好，感谢提供如此优秀的组件。

我看下文档之后，有一个疑惑，不知道4.0.6版本怎么使用？

在 App.js 添加如下之后，如何使用该组件？
`setSiblingWrapper((sibling) => <Provider store={stateStore}>{sibling}</Provider>);`

其他地方需要使用该组件的话，怎么引用呢？

**Comment by sunnylqm** [comment]
只有在你用到类似redux，mobx等需要全局Provider的情况下需要调用此方法，否则不需要使用这个方法
任何地方直接new RootSibling即可

**Comment by niu-da-li** [comment]
> 只有在你用到类似redux，mobx等需要全局Provider的情况下需要调用此方法，否则不需要使用这个方法
> 任何地方直接new RootSiblings即可

明白了，多谢~
