### ISSUE TITLE
modal does not transparent in iPhone 11

### ISSUE THREAD

**Issue by ananiy** [magicismight/react-native-root-siblings#64]
```ts
import React from 'react'

import styled from 'styled-components/native'
import useMount from 'react-use/lib/useMount'

import { Modal } from 'react-native'
import RootSiblings from 'react-native-root-siblings'

const View = styled.View`
  flex: 1;
  background: rgba(255, 255, 0, 0.5);
  justify-content: center;
  align-items: center;
`

const View2 = styled(View)`
  background: #f0f;
`

const Text = styled.Text``

export const Test = () => {
  useMount(() => {
    new RootSiblings(
      (
        <Modal visible transparent={true}>
          <View>
            <Text>Test</Text>
          </View>
        </Modal>
      ),
    )
  })
  return (
    <View2>
      <Text>hello</Text>
    </View2>
  )
}
```

```json
{
  "react-native": "^0.61.5",
  "react-native-root-siblings": "^4.0.6",
}
```

in iPhone 6: 
![IMG_0527](https://user-images.githubusercontent.com/33290601/79959784-1e45e480-84b7-11ea-97e8-aa5f648750bc.PNG)

in iPhone 11:
![IMG_1586](https://user-images.githubusercontent.com/33290601/79959796-2140d500-84b7-11ea-92ba-2631b02c29ec.PNG)

**Comment by sunnylqm** [comment]
Why use modal inside a rootsibling? ... Rootsibling itself is a modal

**Comment by ananiy** [comment]
> Why use modal inside a rootsibling? ... Rootsibling itself is a modal

Rootsibling isn't fullscreen, I just want use like: 
```ts
const modal = new Rootsibling(<Modal>{...}</Modal>)

btn.onClick = () => modal.destory()
```

**Comment by sunnylqm** [comment]
Just make a view that has a full screen style. Modal has a lot of bugs.

**Comment by ananiy** [comment]
> Just make a view that has a full screen style(`StyleSheet.absoluteFillObject`). Modal has a lot of bugs.

My rn code in a native app by another team, so I must use native navigation, Rootsibling using full screen style can't cover native navigation, but Rootsibling with Modal could do it. 

So I have this problem~

**Comment by sunnylqm** [comment]
I still don't get the point. Is there any native ui in your rn view? If no then RootSibling should be ok to cover any views (maybe with an additional `RootSiblingParent` wrapper https://github.com/magicismight/react-native-root-siblings/issues/52#issuecomment-563252331). If not then could you try Modal without RootSibling to confirm where the issue might come from?

**Comment by ananiy** [comment]
> I still don't get the point.
> Is there any native ui in your rn view?
> If No then RootSibling should be ok to cover any views (maybe with an additional `RootSiblingParent` wrapper [#52 (comment)](https://github.com/magicismight/react-native-root-siblings/issues/52#issuecomment-563252331)).
> If Yes then could you try Modal without RootSibling to confirm where the issue might come from?

Yeah, there is a native navigation in my rn view, so RootSibling not cover my screen.

My problem is, this use case is ok in iphone 6 but not in iphone 11, thx

**Comment by sunnylqm** [comment]
I would not consider a native navigation an inner native ui since usually it's kind of a parent container. In this case rootsiblings would work with a parent mount point which i have mentioned above.
If that is not the case, then try modal without rootsiblings then we can know which one caused your issue.
