### ISSUE TITLE
react-native-firebase

### ISSUE THREAD

**Issue by codecopier** [magicismight/react-native-root-siblings#65]
./node_modules/react-native-firebase/dist/utils/events.js
Module not found: Can't resolve 'react-native/Libraries/vendor/emitter/EventEmitter' in 'E\node_modules\react-native-firebase\dist\utils'

when i run react-native run-android working fine when i am trying to run npm run web am getting like this.

**Comment by sunnylqm** [comment]
Sounds you need to ask in react-native-firebase's repo
