### ISSUE TITLE
web端使用 react 有类似react-native-root-siblings的库或者机制吗？

### ISSUE THREAD

**Issue by KingAmo** [magicismight/react-native-root-siblings#67]
如题

**Comment by sunnylqm** [comment]
https://zh-hans.reactjs.org/docs/portals.html

**Comment by KingAmo** [comment]
@sunnylqm `ReactDOM.createPortal()` 返回一个 element,  需要用在`render()`中才能显示--

我想要函数式调用来显示一个toast, 而不是在组件中render出来，怎么实现呢

**Comment by sunnylqm** [comment]
找到一个 https://github.com/minidonut/react-functional-modal

**Comment by magicismight** [comment]
和 react-native 有耦合的地方只有 AppRegistry 这部分，基础逻辑 react 通用。
`src/RootSiblingsManager.tsx` 把里面和 react-native 相关的逻辑去掉就可以了
