### ISSUE TITLE
version 5.0.1 can not work on react-native version 0.74.5 and 0.72.1 

### ISSUE THREAD

**Issue by yzm347404** [magicismight/react-native-root-siblings#81]
after set RootSiblingParent as the root element and call 
let sibling = new RootSiblings(<View
              style={{top: 0,right: 0,bottom: 0,left: 0,backgroundColor: 'red'}}
            />);

show nothing. How to use this version.  But lib react-native-root-toast dependent on this lib works. Any on can help me for this issue?

**Comment by sunnylqm** [comment]
missing position:absolute?

**Comment by yzm347404** [comment]
it works after add position:'absolute'， thx @sunnylqm
