### ISSUE TITLE
Unable to resolve module 'react-native/Libraries/EventEmitter/EventEmitter rn-0.48.2

### ISSUE THREAD

**Issue by efstathiosntonas** [magicismight/react-native-root-siblings#9]
It seems that after this breaking change: https://github.com/facebook/react-native/commit/db3df3400a80353a0140442a5045eca344dfc76f the module is not working anymore.

**Comment by joncrocks** [comment]
It's an earlier change than that I think.

https://github.com/facebook/react-native/commit/365aea3415fdf3e16a6643862a0bfacf87b2f1d1#diff-21131746d55fbfb23814f3310bc4fa1b

Moved a bunch of files, including:

> Libraries/EventEmitter/EventEmitter.js → Libraries/vendor/emitter/EventEmitter.js

**Comment by phips28** [comment]
there are also other libs broken with RN-0.48.x, 
e.g.: https://github.com/invertase/react-native-firebase/pull/387/files

Can someone fix this for 0.48 ?

**Comment by efstathiosntonas** [comment]
This change should go to 49 rc and not in 48 to give space to the devs to make changes. Anyway...

**Comment by baijunjie** [comment]
Same question

**Comment by cbjs** [comment]
+1

**Comment by Sherman-Chen** [comment]
bump

**Comment by lanten** [comment]
+2

**Comment by Almouro** [comment]
I suggested a PR #11 which has no breaking changes. Instead of using the React Native event emitter, it uses a third party one with the same API.
What do you guys think?

In the meantime, it's possible to use the package `@bam.tech/react-native-root-siblings` from npm which has those changes

**Comment by tiaaaa123** [comment]
Hope it get merged soon... even though the creator isn't active much...

**Comment by zhaoxj** [comment]
Fix:
Change import EventEmitter from 'react-native/Libraries/EventEmitter/EventEmitter';
to import EventEmitter from 'react-native/Libraries/vendor/emitter/EventEmitter';
In AppRegistryInjection.js.

**Comment by AshokICreate** [comment]
when this changes going to be merged. please merge asap we are waiting.

**Comment by Sherman-Chen** [comment]
this isnt ever going to be fixed, fork it or move to a better alternative: https://github.com/maxs15/react-native-modalbox

**Comment by Morriz** [comment]
@magicismight Please make your root siblings module work with RN 16+, so we don't have to fork your stuff and create confusion. It will also be the answer to this bug report: https://github.com/magicismight/react-native-root-toast/issues/51

**Comment by Tamiyadd** [comment]
+ 1

**Comment by AshokICreate** [comment]
+1

**Comment by Stoneleee** [comment]
>Fix:
Change import EventEmitter from 'react-native/Libraries/EventEmitter/EventEmitter';
to import EventEmitter from 'react-native/Libraries/vendor/emitter/EventEmitter';
In AppRegistryInjection.js.

On the contrary, I changed to `'react-native/Libraries/EventEmitter/EventEmitter'`
It worked,  unbelievable！

**Comment by Morriz** [comment]
Plz read my previous comment @Stone
